name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Docker image tags
        id: vars
        run: |
          echo "BACKEND_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/foodgram-backend:latest" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/foodgram-frontend:latest" >> $GITHUB_ENV

      - name: Build & push backend
        run: |
          docker build -t $BACKEND_IMAGE ./backend
          docker push $BACKEND_IMAGE

      - name: Build & push frontend
        run: |
          docker build -t $FRONTEND_IMAGE ./frontend
          docker push $FRONTEND_IMAGE

  flake8_lint:
    name: Check Flake8 Linting
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.8.0
        pip install flake8 flake8-isort flake8-pyproject
        pip install -r backend/requirements.txt

    - name: Run flake8
      run: |
        cd backend
        python -m flake8 .
    - name: Lint with ruff
      run: python -m ruff check backend/
